version: "3.9"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_net
networks:
  jenkins_net:
